### ISSUE TITLE
Call to undefined function password_hash()

### ISSUE THREAD

**Issue by Sonny-Fox** [mitchellurgero/bootforums#2]
Installed several times and get the following upon trying to create the first (i.e., admin) user

"PHP Fatal error:  Call to undefined function password_hash() in /path/to/bootforums/db.php on line 46"

This error occurs in both the browser window in addition to error_log.

Apachie version 2.4.23, PHP version 5.4.45

**Comment by mitchellurgero** [comment]
Update to PHP 5.6 as password_hash function does not exist in PHP 5.4

**Comment by Sonny-Fox** [comment]
Thanks for the confirmation. Since I don't currently have the option to upgrade due to other software compatibility issues I was able to successfully operate the program by utilizing another GitHub project, password_compat, which provides compatibility under PHP 5.4.

**Comment by mitchellurgero** [comment]
Awesome! Good luck my friend.
