### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by AirForce11** [mitchellurgero/bootforums#4]
if someone holds a key down long enough in posting, it looks like it goes to the next line underneath, but when a user submits the post, it does not insert a line break in there so the held down key letter goes to the right, and right off the forums area. this ruins the look of the entire board.

**Comment by mitchellurgero** [comment]
Can you screenshot an example?

**Comment by AirForce11** [comment]
![image](https://user-images.githubusercontent.com/28614185/39441942-945a1f48-4c7d-11e8-886b-30cb623a0c44.png)

ti the right, it just keeps going forever.

**Comment by AirForce11** [comment]
it keeps going to the right, way past the box. It makes the browser open up a left and right scroll. On a cell phone this breaks the entire look. Thanks 4 the response!!

**Comment by AirForce11** [comment]
to recreate, just hold a key down. in this case the 3- you have to hold it down long enough, it looks like its wrapping to the next line in the input area, but after you post it, it goes straight to the right.

**Comment by mitchellurgero** [comment]
I dont have an instance of bootforums setup and I can't set one up at the moment, so a screenshot would help but I think I have a fix in mind.

**Comment by AirForce11** [comment]
cool!! i sent a screen shot its a couple of posts up

**Comment by mitchellurgero** [comment]
Oh! I see it lol

**Comment by AirForce11** [comment]
here is a direct link so you can see... https://www.mckayla.news/bfor/post.php?page=1&type=view&post=test3     its a test forum, i only did that to "test 3"


not sure if ur familiar with it, but the old imageboard "tinyib" the flatfile chan board has the same prob.

**Comment by mitchellurgero** [comment]
Try latest commit for that.

**Comment by mitchellurgero** [comment]
Because the browser is "seeing" that as one word it wont wrap it, the overflow in css that I put *should* fix it..

**Comment by AirForce11** [comment]
cool, thanks bro! Its not totally fixed but it is better, you can click on the same link above to see what it did. it puts the right left scroll inline, which is a lot better!!!!!!!!!! 
![image](https://user-images.githubusercontent.com/28614185/39442824-8eedfbe4-4c80-11e8-898e-2a2f5a709372.png)

**Comment by mitchellurgero** [comment]
Yea - try putting spaces between the 3's - it's a browser issue idk if I can have a perfect fix for it, but I'll keep looking

**Comment by AirForce11** [comment]
no hurry, thank you so much for the prompt reply. The way it is now is much better! Thanks so much!

**Comment by AirForce11** [comment]
im trying 2 pay with a credit card by the way. like when i buy something without a paypal account it usually lets me enter card info anyway and buy stuff as a guest.

**Comment by mitchellurgero** [comment]
You can try: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=mitchell%40urgero%2eorg&lc=US&no_note=1&no_shipping=1&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_LG%2egif%3aNonHosted

**Comment by AirForce11** [comment]
that one worked, it took the credit card with no account. you can delete all the text if ya want or if ya want me to let me know thanks!!!!!!!!!       ![image](https://user-images.githubusercontent.com/28614185/39443950-0f13d336-4c84-11e8-9bd1-dd355ed63583.png)

**Comment by mitchellurgero** [comment]
Oh my god, thank you! That is so generous of you! <3

**Comment by AirForce11** [comment]
no problem. thanks for your kindness in helping a stranger with the issue.

**Comment by AirForce11** [comment]
do you want me to delete the first post i made or keep it there?

**Comment by mitchellurgero** [comment]
Leave it for completion.

**Comment by mitchellurgero** [comment]
@AirForce11 - Try the latest commit  I added CSS to force word wrap even for words (so they break line)

**Comment by AirForce11** [comment]
Cool, i didn't even see you replied again, sry. It totally fixed all line break issues, a test can be viewed here. Thanks!!!! https://www.mckayla.news/bfor/post.php?page=1&type=view&post=test-of-latest-commit

**Comment by AirForce11** [comment]
And it fixed the old test example  as well , thanks!!!!!!!!!! https://www.mckayla.news/bfor/post.php?page=1&type=view&post=test3
