### ISSUE TITLE
wysiwyg editor

### ISSUE THREAD

**Issue by ghost** [mitchellurgero/bootforums#8]
was wondering if it would be difficult to incorporate the simple blog wysiwyg editor into the forum?

**Comment by mitchellurgero** [comment]
It wouldn't be, but as of right now this project is on a "security updates only" status so it wont get it officially any time soon.

**Comment by simon511000** [comment]
Like this ? : https://www.youtube.com/watch?v=Wye8BWd3d2A

**Comment by mitchellurgero** [comment]
Should be fixed in https://github.com/mitchellurgero/bootforums/commit/0efd1c9e3ae2780dd9c2901eaa258bde080d22d4
